allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

subprojects {
    plugins.withId("com.android.library") {
        android {
            if (namespace == null) {
                def mf = file("src/main/AndroidManifest.xml")
                if (mf.exists()) {
                    def parsed = new groovy.util.XmlSlurper().parse(mf)
                    namespace = parsed.@package.text()
                }
            }
        }
    }
}
