#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/flowline/flowline /usr/bin/flowline

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/flowline.service ]; then
			rm /etc/systemd/system/flowline.service /usr/lib/systemd/system/flowline.service /usr/lib/systemd/user/flowline.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/flowline/files/systemd/flowline.service /usr/lib/systemd/system/flowline.service
		# try fix error in Ubuntu 18.04
		# Failed to reload flowline.service: Unit flowline.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/flowline.service:10: Executable path is not absolute: pkill -f "flowline --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/flowline.service
		fi
		systemctl daemon-reload
		systemctl enable flowline
		systemctl start flowline
	fi
fi